### ISSUE TITLE
多进程以及service绑定之间的问题

### ISSUE THREAD

**Issue by zengjingfang** [zengjingfang/AndroidBox#20]

**Comment by zengjingfang** [comment]
###  unbindService 

```java

if (serviceConnection != null) {
            try {
                context.unbindService(serviceConnection);
            } catch (Exception e) {
                LogUtil.w(TAG, "unbindService Exception:" + e.toString());
            }

        } else {
            LogUtil.w(TAG, "serviceConnection is null.");
        }

// 异常
Exception:java.lang.IllegalArgumentException: Service not registered: 

com.xtc.im.core.app.bridge.PushServiceManager$PushServiceConnection@284edeeb
```

**Comment by zengjingfang** [comment]
### Binder.java
```java
    private static final void sendDeathNotice(DeathRecipient recipient) {
        if (false) Log.v("JavaBinder", "sendDeathNotice to " + recipient);
        try {
            recipient.binderDied();
        }
        catch (RuntimeException exc) {
            Log.w("BinderNative", "Uncaught exception from death notification",
                    exc);
        }
    }
```
### LoadedApk.java
```java
 public void death(ComponentName name, IBinder service) {
            ServiceDispatcher.ConnectionInfo old;

            synchronized (this) {
                mDied = true;
                old = mActiveConnections.remove(name);
                if (old == null || old.binder != service) {
                    // Death for someone different than who we last
                    // reported...  just ignore it.
                    return;
                }
                old.binder.unlinkToDeath(old.deathMonitor, 0);
            }

            if (mActivityThread != null) {
                mActivityThread.post(new RunConnection(name, service, 1));
            } else {
                doDeath(name, service);
            }
        }

        public void doDeath(ComponentName name, IBinder service) {
           // disconnected 回调
            mConnection.onServiceDisconnected(name);
        }
```

**Comment by zengjingfang** [comment]
### 问题二：Not allowed to start service Intent
```java
java.lang.IllegalStateException: Not allowed to start service Intent { act=com.xtc.im.core.push.PushService flg=0x20 pkg=com.xtc.watch cmp=com.xtc.watch/com.xtc.im.core.push.PushService (has extras) }:
app is in background uid UidRecord{1922d78 u0a169 SVC idle change:idle|uncached procs:1 seq(0,0,0)}
at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1521)
at android.app.ContextImpl.startService(ContextImpl.java:1477)
at android.content.ContextWrapper.startService(ContextWrapper.java:650)
at com.xtc.im.core.app.bridge.PushServiceManager.init(PushServiceManager.java:104)
at com.xtc.im.core.app.IMCore$16.run(IMCore.java:903)
at java.lang.Thread.run(Thread.java:764)
```
