### ISSUE TITLE
Android8.0系统：.RemoteServiceException: Bad notification for startForeground

### ISSUE THREAD

**Issue by zengjingfang** [zengjingfang/AndroidBox#23]
### 问题：启动push进程失败

启动的时候发现push进程起来了，但是立即弹出“停止运行”，查看Log有如下异常：

```java
Process: com.xtc.watch:push, PID: 12789
android.app.RemoteServiceException: Bad notification for startForeground: java.lang.RuntimeException: invalid channel for service notification: Notification(channel=null pri=0 contentView=null vibrate=null sound=null defaults=0x0 flags=0x40 color=0x00000000 vis=PRIVATE)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1768)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loop(Looper.java:164)
at android.app.ActivityThread.main(ActivityThread.java:6494)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```
点击确认，发现Push进程已挂，随后Log出现如下异常：

```java
java.lang.IllegalStateException: Not allowed to start service Intent { act=com.xtc.im.core.push.PushService flg=0x20 pkg=com.xtc.watch cmp=com.xtc.watch/com.xtc.im.core.push.PushService (has extras) }:
app is in background uid UidRecord{1922d78 u0a169 SVC idle change:idle|uncached procs:1 seq(0,0,0)}
at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1521)
at android.app.ContextImpl.startService(ContextImpl.java:1477)
at android.content.ContextWrapper.startService(ContextWrapper.java:650)
at com.xtc.im.core.app.bridge.PushServiceManager.init(PushServiceManager.java:104)
at com.xtc.im.core.app.IMCore$16.run(IMCore.java:903)
at java.lang.Thread.run(Thread.java:764)
```

**Comment by zengjingfang** [comment]
```java
Error showing notification for service
java.lang.RuntimeException: invalid channel for service notification: Notification(channel=null pri=0 contentView=null vibrate=null sound=null defaults=0x0 flags=0x40 color=0x00000000 vis=PRIVATE)
at com.android.server.am.ServiceRecord$1.run(ServiceRecord.java:532)
at android.os.Handler.handleCallback(Handler.java:790)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:164)
at android.os.HandlerThread.run(HandlerThread.java:65)
at com.android.server.ServiceThread.run(ServiceThread.java:46)
```

**Comment by zengjingfang** [comment]
Unable to load resource 0x7f030000 from pkg=com.xtc.im.phonesample
                                       android.content.res.Resources$NotFoundException: Drawable com.xtc.im.phonesample:mipmap/ic_launcher with resource ID #0x7f030000
                                       Caused by: android.content.res.Resources$NotFoundException: File res/mipmap-anydpi-v26/ic_launcher.xml from drawable resource ID #0x7f030000
                                           at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:820)
                                           at android.content.res.ResourcesImpl.loadDrawable(ResourcesImpl.java:630)
                                           at android.content.res.Resources.getDrawableForDensity(Resources.java:877)
                                           at android.content.res.Resources.getDrawable(Resources.java:819)
                                           at android.graphics.drawable.Icon.loadDrawableInner(Icon.java:324)
                                           at android.graphics.drawable.Icon.loadDrawable(Icon.java:277)
                                           at android.graphics.drawable.Icon.loadDrawableAsUser(Icon.java:388)

**Comment by SocratesR** [comment]
what’s the type definition about "notificationId"?
