### ISSUE TITLE
SQLiteDiskIOException: disk I/O error - SQLITE_IOERR_WRITE

### ISSUE THREAD

**Issue by zengjingfang** [zengjingfang/AndroidBox#27]

**Comment by zengjingfang** [comment]
### 资料查询

https://www.sqlite.org/rescode.html

### 官方解释

The SQLITE_IOERR_WRITE error code is an extended error code for SQLITE_IOERR indicating an I/O error in the VFS layer while trying to write into a file on disk. This error might result from a hardware malfunction or because a filesystem came unmounted while the file was open. This error should not occur if the filesystem is full as there is a separate error code (SQLITE_FULL) for that purpose.

>  获取信息

+ 设备故障
+ 文件打开时正在卸载文件系统导致

**Comment by zengjingfang** [comment]
### 异常详情  pro5 出现1次

java.lang.IllegalStateException: attempt to re-open an already-closed object: SQLiteDatabase: /data/user/0/com.xtc.watch/databases/xtc_im.db
	at android.database.sqlite.SQLiteClosable.acquireReference(SQLiteClosable.java:55)
	at android.database.sqlite.SQLiteDatabase.endTransaction(SQLiteDatabase.java:522)
	at com.xtc.im.core.push.store.dao.ServerConfigDao.update(Unknown Source)
	at com.xtc.im.core.push.domain.DomainManager.updateOnConnectFailed(Unknown Source)
	at com.xtc.im.core.push.PushService$1$4.run(Unknown Source)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.os.HandlerThread.run(HandlerThread.java:61)
