### ISSUE TITLE
Activity的生命周期

### ISSUE THREAD

**Issue by zengjingfang** [zengjingfang/AndroidBox#29]

**Comment by zengjingfang** [comment]
ACTIVITY MANAGER RECENT TASKS (dumpsys activity recents)

  Recent tasks:

  * Recent #0: TaskRecord{7ebd2b5 #653 A=com.xtc.watch U=0 sz=1}

  * Recent #1: TaskRecord{36a26b47 #630 A=com.bbk.launcher2 U=0 sz=1}

### 在主页

ACTIVITY MANAGER ACTIVITIES (dumpsys activity activities)

Display #0 (activities from top to bottom):

  Stack #1:

    Task id #653

      TaskRecord{7ebd2b5 #653 A=com.xtc.watch U=0 sz=1}

      Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x30200000 cmp=com.xtc.watch/.MainActivity }

        Hist #0: ActivityRecord{1e44eb8 u0 com.xtc.watch/.view.home.activity.XtcHomeActivity t653}

          Intent { flg=0x10000000 cmp=com.xtc.watch/.view.home.activity.XtcHomeActivity }

          ProcessRecord{1198539a 18225:com.xtc.watch/u0a643}



    Running activities (most recent first):

      TaskRecord{7ebd2b5 #653 A=com.xtc.watch U=0 sz=1}

        Run #0: ActivityRecord{1e44eb8 u0 com.xtc.watch/.view.home.activity.XtcHomeActivity t653}



    mResumedActivity: ActivityRecord{1e44eb8 u0 com.xtc.watch/.view.home.activity.XtcHomeActivity t653}

###  启动另一个activity之后

ACTIVITY MANAGER ACTIVITIES (dumpsys activity activities)

Display #0 (activities from top to bottom):

  Stack #1:

    Task id #653

      TaskRecord{7ebd2b5 #653 A=com.xtc.watch U=0 sz=2}

      Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x30200000 cmp=com.xtc.watch/.MainActivity }

        Hist #1: ActivityRecord{2444bff0 u0 com.xtc.watch/.view.schoolguard.activity.SchoolGuardRecordActivity t653}

          Intent { flg=0x10000000 cmp=com.xtc.watch/.view.schoolguard.activity.SchoolGuardRecordActivity }

          ProcessRecord{1198539a 18225:com.xtc.watch/u0a643}

        Hist #0: ActivityRecord{1e44eb8 u0 com.xtc.watch/.view.home.activity.XtcHomeActivity t653}

          Intent { flg=0x10000000 cmp=com.xtc.watch/.view.home.activity.XtcHomeActivity }

          ProcessRecord{1198539a 18225:com.xtc.watch/u0a643}



    Running activities (most recent first):

      TaskRecord{7ebd2b5 #653 A=com.xtc.watch U=0 sz=2}

        Run #1: ActivityRecord{2444bff0 u0 com.xtc.watch/.view.schoolguard.activity.SchoolGuardRecordActivity t653}

        Run #0: ActivityRecord{1e44eb8 u0 com.xtc.watch/.view.home.activity.XtcHomeActivity t653}



    mResumedActivity: ActivityRecord{2444bff0 u0 com.xtc.watch/.view.schoolguard.activity.SchoolGuardRecordActivity t653}

###  再次启动一个
ACTIVITY MANAGER ACTIVITIES (dumpsys activity activities)

Display #0 (activities from top to bottom):

  Stack #1:

    Task id #653

      TaskRecord{7ebd2b5 #653 A=com.xtc.watch U=0 sz=3}

      Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x30200000 cmp=com.xtc.watch/.MainActivity }

        Hist #2: ActivityRecord{1d1aeae6 u0 com.xtc.watch/.view.schoolguard.activity.GuardAddressSelectActivity t653}

          Intent { cmp=com.xtc.watch/.view.schoolguard.activity.GuardAddressSelectActivity (has extras) }

          ProcessRecord{1198539a 18225:com.xtc.watch/u0a643}

        Hist #1: ActivityRecord{2444bff0 u0 com.xtc.watch/.view.schoolguard.activity.SchoolGuardRecordActivity t653}

          Intent { flg=0x10000000 cmp=com.xtc.watch/.view.schoolguard.activity.SchoolGuardRecordActivity }

          ProcessRecord{1198539a 18225:com.xtc.watch/u0a643}

        Hist #0: ActivityRecord{1e44eb8 u0 com.xtc.watch/.view.home.activity.XtcHomeActivity t653}

          Intent { flg=0x10000000 cmp=com.xtc.watch/.view.home.activity.XtcHomeActivity }

          ProcessRecord{1198539a 18225:com.xtc.watch/u0a643}



    Running activities (most recent first):

      TaskRecord{7ebd2b5 #653 A=com.xtc.watch U=0 sz=3}

        Run #2: ActivityRecord{1d1aeae6 u0 com.xtc.watch/.view.schoolguard.activity.GuardAddressSelectActivity t653}

        Run #1: ActivityRecord{2444bff0 u0 com.xtc.watch/.view.schoolguard.activity.SchoolGuardRecordActivity t653}

        Run #0: ActivityRecord{1e44eb8 u0 com.xtc.watch/.view.home.activity.XtcHomeActivity t653}



    mResumedActivity: ActivityRecord{1d1aeae6 u0 com.xtc.watch/.view.schoolguard.activity.GuardAddressSelectActivity t653}


### 在启动

CTIVITY MANAGER ACTIVITIES (dumpsys activity activities)

Display #0 (activities from top to bottom):

  Stack #1:

    Task id #653

      TaskRecord{7ebd2b5 #653 A=com.xtc.watch U=0 sz=4}

      Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x30200000 cmp=com.xtc.watch/.MainActivity }

        Hist #3: ActivityRecord{3a27eb53 u0 com.xtc.watch/.view.schoolguard.activity.GuardAddressEditActivity t653}

          Intent { cmp=com.xtc.watch/.view.schoolguard.activity.GuardAddressEditActivity (has extras) }

          ProcessRecord{1198539a 18225:com.xtc.watch/u0a643}

        Hist #2: ActivityRecord{1d1aeae6 u0 com.xtc.watch/.view.schoolguard.activity.GuardAddressSelectActivity t653}

          Intent { cmp=com.xtc.watch/.view.schoolguard.activity.GuardAddressSelectActivity (has extras) }

          ProcessRecord{1198539a 18225:com.xtc.watch/u0a643}

        Hist #1: ActivityRecord{2444bff0 u0 com.xtc.watch/.view.schoolguard.activity.SchoolGuardRecordActivity t653}

          Intent { flg=0x10000000 cmp=com.xtc.watch/.view.schoolguard.activity.SchoolGuardRecordActivity }

          ProcessRecord{1198539a 18225:com.xtc.watch/u0a643}

        Hist #0: ActivityRecord{1e44eb8 u0 com.xtc.watch/.view.home.activity.XtcHomeActivity t653}

          Intent { flg=0x10000000 cmp=com.xtc.watch/.view.home.activity.XtcHomeActivity }

          ProcessRecord{1198539a 18225:com.xtc.watch/u0a643}



    Running activities (most recent first):

      TaskRecord{7ebd2b5 #653 A=com.xtc.watch U=0 sz=4}

        Run #3: ActivityRecord{3a27eb53 u0 com.xtc.watch/.view.schoolguard.activity.GuardAddressEditActivity t653}

        Run #2: ActivityRecord{1d1aeae6 u0 com.xtc.watch/.view.schoolguard.activity.GuardAddressSelectActivity t653}

        Run #1: ActivityRecord{2444bff0 u0 com.xtc.watch/.view.schoolguard.activity.SchoolGuardRecordActivity t653}

        Run #0: ActivityRecord{1e44eb8 u0 com.xtc.watch/.view.home.activity.XtcHomeActivity t653}



    mResumedActivity: ActivityRecord{3a27eb53 u0 com.xtc.watch/.view.schoolguard.activity.GuardAddressEditActivity t653}

**Comment by zengjingfang** [comment]
###  启动activity的问题

android.util.AndroidRuntimeException: Calling startActivity() from outside of an Activity  context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want?
	at android.app.ContextImpl.startActivity(ContextImpl.java:1056)
	at android.app.ContextImpl.startActivity(ContextImpl.java:1043)
	at android.content.ContextWrapper.startActivity(ContextWrapper.java:319)
	at com.xtc.common.onlinestatus.displayer.OnlineStaView.handleClick(OnlineStaView.java:129)
	at com.xtc.common.onlinestatus.displayer.OnlineStaView$1.onClick(OnlineStaView.java:58)
	at android.view.View.performClick(View.java:4457)
	at android.view.View$PerformClick.run(View.java:18477)
	at android.os.Handler.handleCallback(Handler.java:733)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:5113)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:780)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:596)
	at dalvik.system.NativeStart.main(Native Method)

### ContextImpl.java
```java

 @Override
    public void startActivity(Intent intent, Bundle options) {
        warnIfCallingFromSystemProcess();

        // Calling start activity from outside an activity without FLAG_ACTIVITY_NEW_TASK is
        // generally not allowed, except if the caller specifies the task id the activity should
        // be launched in.
        if ((intent.getFlags()&Intent.FLAG_ACTIVITY_NEW_TASK) == 0
                && options != null && ActivityOptions.fromBundle(options).getLaunchTaskId() == -1) {
            throw new AndroidRuntimeException(
                    "Calling startActivity() from outside of an Activity "
                    + " context requires the FLAG_ACTIVITY_NEW_TASK flag."
                    + " Is this really what you want?");
        }
        mMainThread.getInstrumentation().execStartActivity(
                getOuterContext(), mMainThread.getApplicationThread(), null,
                (Activity) null, intent, -1, options);
    }
```
