### ISSUE TITLE
java.lang.IllegalStateException: Fragment already added

### ISSUE THREAD

**Issue by zengjingfang** [zengjingfang/AndroidBox#32]
STACK_TRACE=java.lang.IllegalStateException: Fragment already added: LocationMainFragment
                                                      at android.support.v4.app.FragmentManagerImpl.addFragment(FragmentManager.java:1891)
                                                      at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:760)
                                                      at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2596)
                                                      at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2383)
                                                      at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2338)
                                                      at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2245)
                                                      at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:703)
                                                      at android.os.Handler.handleCallback(Handler.java:739)
                                                      at android.os.Handler.dispatchMessage(Handler.java:95)
                                                      at android.os.Looper.loop(Looper.java:135)
                                                      at android.app.ActivityThread.main(ActivityThread.java:5401)
                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                      at java.lang.reflect.Method.invoke(Method.java:372)
                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:919)
                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:714)

**Comment by zengjingfang** [comment]
### 源码追踪

#### FragmentManager.java
```java

 public void addFragment(Fragment fragment, boolean moveToStateNow) {
        if (DEBUG) Log.v(TAG, "add: " + fragment);
        makeActive(fragment);
        if (!fragment.mDetached) {
            if (mAdded.contains(fragment)) {
                throw new IllegalStateException("Fragment already added: " + fragment);
            }
            synchronized (mAdded) {
                mAdded.add(fragment);
            }
            fragment.mAdded = true;
            fragment.mRemoving = false;
            if (fragment.mView == null) {
                fragment.mHiddenChanged = false;
            }
            if (fragment.mHasMenu && fragment.mMenuVisible) {
                mNeedMenuInvalidate = true;
            }
            if (moveToStateNow) {
                moveToState(fragment);
            }
        }
    }
```

#### 观察fragment.mAdded

+  初始值为false
      +  initState
+  设置为true
       + attachFragment
       + addFragment
+  设置为false
       + removeFragment
       + detachFragment
