### ISSUE TITLE
Native闪退

### ISSUE THREAD

**Issue by zengjingfang** [zengjingfang/AndroidBox#41]
```java
06-21 10:36:51.901 18665-18945/com.xtc.watch A/libc: heap corruption detected by dlmalloc_real
06-21 10:36:51.901 18665-18945/com.xtc.watch A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 18945 (Thread-3956)
06-21 10:36:53.581 1241-18958/? E/test: key length=16
06-21 10:36:53.591 1241-18958/? E/test: decodePrivate 22
06-21 10:36:54.051 875-1143/? E/NativeCrashListener: Exception dealing with report
                                                     android.system.ErrnoException: read failed: EAGAIN (Try again)
                                                         at libcore.io.Posix.readBytes(Native Method)
                                                         at libcore.io.Posix.read(Posix.java:165)
                                                         at libcore.io.BlockGuardOs.read(BlockGuardOs.java:230)
                                                         at android.system.Os.read(Os.java:350)
                                                         at com.android.server.am.NativeCrashListener.consumeNativeCrashData(NativeCrashListener.java:240)
                                                         at com.android.server.am.NativeCrashListener.run(NativeCrashListener.java:138)
```

**Comment by zengjingfang** [comment]
signal 6 (SIGABRT)::
导致该错误的原因：调用了abort函数
