### ISSUE TITLE
Component class com.huawei.hms.support.api.push.PushEventReceiver does not exist in com.xtc.watch

### ISSUE THREAD

**Issue by zengjingfang** [zengjingfang/AndroidBox#47]
07-25 09:51:01.897 25436-25436/com.xtc.watch E/AndroidRuntime: FATAL EXCEPTION: main
                                                               Process: com.xtc.watch, PID: 25436
                                                               java.lang.RuntimeException: Unable to create application com.xtc.watch.XtcApplication: java.lang.IllegalArgumentException: Component class com.huawei.hms.support.api.push.PushEventReceiver does not exist in com.xtc.watch
                                                                   at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4701)
                                                                   at android.app.ActivityThread.access$1600(ActivityThread.java:167)
                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1435)
                                                                   at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                   at android.os.Looper.loop(Looper.java:135)
                                                                   at android.app.ActivityThread.main(ActivityThread.java:5401)
                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                   at java.lang.reflect.Method.invoke(Method.java:372)
                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:919)
                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:714)
                                                                Caused by: java.lang.IllegalArgumentException: Component class com.huawei.hms.support.api.push.PushEventReceiver does not exist in com.xtc.watch
                                                                   at android.os.Parcel.readException(Parcel.java:1550)
                                                                   at android.os.Parcel.readException(Parcel.java:1499)
                                                                   at android.content.pm.IPackageManager$Stub$Proxy.setComponentEnabledSetting(IPackageManager.java:3394)
                                                                   at android.app.ApplicationPackageManager.setComponentEnabledSetting(ApplicationPackageManager.java:1492)
                                                                   at com.xtc.im.phone.thirdpush.a.d(ThirdPushManager.java:242)
                                                                   at com.xtc.im.phone.thirdpush.a.b(ThirdPushManager.java:132)
                                                                   at com.xtc.im.phone.IMPhone.startThirdPush(IMPhone.java:154)
                                                                   at com.xtc.watch.XtcApplication.onCreate(XtcApplication.java:142)
                                                                   at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1018)
                                                                   at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4698)
                                                                   at android.app.ActivityThread.access$1600(ActivityThread.java:167) 
                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1435) 
                                                                   at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                   at android.os.Looper.loop(Looper.java:135) 
                                                                   at android.app.ActivityThread.main(ActivityThread.java:5401) 
                                                                   at java.lang.reflect.Method.invoke(Native Method) 
                                                                   at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:919) 
                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:714)

**Comment by zengjingfang** [comment]
### 源码追踪

    private final IPackageManager mPM;

    protected ApplicationPackageManager(ContextImpl context,
                              IPackageManager pm) {
        mContext = context;
        mPM = pm;
    }

    @Override
    public void setComponentEnabledSetting(ComponentName componentName,
                                           int newState, int flags) {
        try {
            mPM.setComponentEnabledSetting(componentName, newState, flags, mContext.getUserId());
        } catch (RemoteException e) {
            throw e.rethrowFromSystemServer();
        }
    }

**Comment by zengjingfang** [comment]
###  分析

在hasComponentClassName返回为false的情况下，抛出了异常。而返回false的原因是在manifest中没有找到该组件。但是查看分析代码，在依赖的aar中已经注册了，不知为什么没有起效果。在主工程项目中注册PushEventReceiver，验证OK.
