### ISSUE TITLE
单元测试填坑录

### ISSUE THREAD

**Issue by zengjingfang** [zengjingfang/AndroidBox#7]

**Comment by zengjingfang** [comment]
```java
java.lang.UnsupportedOperationException: elapsedRealtime is native
	at android.os.SystemClock.elapsedRealtime(SystemClock.java)
```

**Comment by zengjingfang** [comment]
#  使用的框架

+  powermock
+  junit

**Comment by zengjingfang** [comment]
# Mock Static 方法

### 先mock这个类

``java
@PrepareForTest({ ScreenUtil.class, NetUtil.class})

PowerMockito.mockStatic(NetUtil.class);
``
### 正确

``java
PowerMockito.when(NetUtil.getNetworkTag(context)).thenReturn("networkTag");
``
### 错误

```java
// 执行代码
PowerMockito.doReturn("networkTag").when(NetUtil.getNetworkTag(context));
//报的异常
org.mockito.exceptions.misusing.UnfinishedStubbingException: 
Unfinished stubbing detected here:
-> at com.xtc.im.core.push.heartbeat.state.ActiveStateTest.heartbeat0(ActiveStateTest.java:59)

E.g. thenReturn() may be missing.
Examples of correct stubbing:
    when(mock.isOk()).thenReturn(true);
    when(mock.isOk()).thenThrow(exception);
    doThrow(exception).when(mock).someVoidMethod();
Hints:
 1. missing thenReturn()
 2. you are trying to stub a final method, you naughty developer!
 3: you are stubbing the behaviour of another mock inside before 'thenReturn' instruction if completed


	at org.powermock.core.MockGateway.doMethodCall(MockGateway.java:124)
	at org.powermock.core.MockGateway.methodCall(MockGateway.java:63)
	at com.xtc.im.core.common.utils.NetUtil.getNetworkTag(NetUtil.java)
```
